## This pair of functions allow to create a matrix as an function type of object, and obtain its inverse matrix
## without re-processing it by storing inverse calculation results on a variable that resides in the scope of
## this function object type and acts as a cache 


## This function takes as argument a matrix and returns a function that contains passed matrix and can also
## contain its inverse. The funtion contains inner functions that can get and set the original matrix and 
## its inverse

makeCacheMatrix <- function(x = matrix()) {
        i_m <- NULL
        set <- function(y) {
                x <<- y
                i_m <<- NULL
        }
        get <- function() x
        setInverseMatrix <- function(inverse) i_m <<- inverse
        getInverseMatrix <- function() i_m
        list(set = set, get = get,
             setInverseMatrix = setInverseMatrix,
             getInverseMatrix = getInverseMatrix)
}


## This function takes as argument a function type object generated by makeCacheMatrix function above, and 
## returns its inverse. It inverse hasn't been calculated before, and therefore it's not stored in the function
## object, this function will compute matrix's inverse, store it on the function like matrix and return it

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        i_m <- x$getInverseMatrix()
        if(!is.null(i_m)) {
                message("getting cached data")
                return(i_m)
        }
        matrix <- x$get()
        i_m <- solve(matrix, ...)
        x$setInverseMatrix(i_m)
        i_m
}
